proyectowww/apps/eventos/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^crear$', crear_evento, name ='crear_evento'),
    url(r'^modificar/(?P<id_evento>\d+)$', modificar_evento, name ='evento_modificar'),
    url(r'^listar$', ListarEventos.as_view(), name = 'evento_listar'),

    url(r'^desactivar/(?P<id_evento>\d+)$', desactivar_evento, name='evento_desactivar'),
    url(r'^activar/(?P<id_evento>\d+)$', activar_evento, name = 'evento_activar'),

    url(r'^ver/inscripcion/(?P<evento_id>[0-9]+)$', inscribir_en_evento, name='inscribir_en_evento'),
    url(r'^ver/escarapela/(?P<evento_id>[0-9]+)/(?P<participante_id>[0-9]+)$', crear_escarapela, name= 'crear_escarapela'),
    url(r'^ver/(?P<evento_id>[0-9]+)/pre_inscripcion$', pre_inscripcion, name ='evento_pre_inscripcion'),
    url(r'^ver/(?P<evento_id>[0-9]+)/$', detalles_evento, name = 'detalles_evento'),
    url(r'^ver/(?P<evento_id>[0-9]+)/calendario$', CalendarioEvento, name = 'calendario_evento'),
    url(r'^calendario/datos$', datos_calendario, name = 'evento_datos_calendario'),

    url(r'^preinscrito/(?P<evento_id>[0-9]+)/listado$', listar_preinscrito, name='listar_preinscrito'),
    url(r'^participante/codigo', participante_ingresar_codigo, name='participante_codigo_participante'),
    url(r'^participante/modificar$', participante_modificar_datos_personales, name= 'participante_modificar'),
    url(r'^participante/modificar/(?P<evento_id>\d+)/(?P<participante_id>\d+)$', participante_modificar, name= 'participante_modificar'),
    url(r'^preinscrito/aceptar/(?P<evento_id>\d+)/(?P<inscripcion_id>\d+)$', aceptar_preinscrito, name= 'aceptar_preinscrito'),
    url(r'^preinscrito/rechazar/(?P<evento_id>\d+)/(?P<inscripcion_id>\d+)$', rechazar_preinscrito, name= 'rechazar_preinscrito'),

    url(r'^recuperar-codigo', recuperar_codigo, name='evento_recuperar_codigo'),
]

proyectowww/proyectowww/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuarios/', include('apps.usuario.urls')),
    url(r'^eventos/', include('apps.eventos.urls')),
    url(r'^noticias/', include('apps.noticias.urls')),
    url(r'^actividad/',include('apps.actividad.urls')),

    url(r'^',include('apps.landing_page.urls')),
    url(r'^reporte/',include('apps.reporte.urls')),
    url(r'^select2/', include('django_select2.urls')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

proyectowww/apps/eventos/models.py
from django.db import models
from django.urls import reverse_lazy

from proyectowww.utilidades import enviar_email

def crear_ruta_evento(instance, filename):
    return "fotos-evento/%s-%s"%(instance.id, filename.encode('ascii','ignore'))



class Evento(models.Model):

    ESTADOS = (
        ('Activo', 'Activo'),
        ('Inactivo', 'Inactivo')
    )

    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    descripcion = models.CharField(max_length=2000, verbose_name="Descripción")
    lugar = models.CharField(max_length=140, verbose_name="Lugar")
    direccion = models.CharField(max_length=140, verbose_name="Dirección")
    telefono = models.CharField(max_length=15, verbose_name="Teléfono")
    costo = models.PositiveIntegerField(default=1, verbose_name="Costo")
    estado = models.CharField(max_length=20, choices = ESTADOS, default='Activo', verbose_name="Estado")
    imagen = models.ImageField(upload_to=crear_ruta_evento, blank=True,help_text='Seleccione una imagen de perfil', verbose_name="Imagen")

    numero_cupos = models.PositiveIntegerField(default=1,verbose_name="Número de cupos")
    fecha_limite_inscripcion = models.DateTimeField(blank=False,null=False, verbose_name="Fecha límite de inscripción")
    fecha_inicio = models.DateTimeField(blank=False,null=False, verbose_name="Fecha inicio")
    fecha_fin = models.DateTimeField(blank=False,null=False, verbose_name="Fecha fin")


    def is_active(self):
        if(self.estado == 'Activo'):
            return True
        else:
            return False


    @staticmethod
    def revisar_existencia_evento(evento):
        try:
            evento = Evento.objects.get(id=evento)
            return evento
        except Exception:
            pass
        return False

    def __str__(self):
        return "%s (%s)"%(self.nombre,self.descripcion)

    @staticmethod
    def obtener_eventos():
        try:
            evento = Evento.objects.all()
            return evento
        except Exception as e:
            raise e
        return False

    # @staticmethod
    # def revisar_existencia_evento(nombre_evento):
    #     try:
    #         evento = Evento.objects.get(nombre=nombre_evento)
    #         return evento
    #     except Exception as e:
    #         raise e
    #     return False


class Participante(models.Model):

    nombres = models.CharField(max_length = 90, verbose_name="Nombres")
    apellidos = models.CharField(max_length = 90, verbose_name="Apellidos")
    correo = models.EmailField(max_length = 254, unique = True, verbose_name="Correo electrónico")
    numero_documento = models.CharField(max_length = 17, unique = True, verbose_name="Número de documento")
    telefono = models.CharField(max_length = 20, unique = True, verbose_name="Teléfono")


    @staticmethod
    def revisar_existencia_participante(documento):
        try:
            participante = Participante.objects.get(numero_documento = documento)
            return participante
        except Exception as e:
            return None
        return None

    @staticmethod
    def revisar_existencia_participante_id(id_participante):
        try:
            participante = Participante.objects.get(id = id_participante)
            return participante
        except Exception as e:
            return None
        return None

    @staticmethod
    def revisar_existencia_participante_correo(correo):
        try:
            participante = Participante.objects.get(correo=correo)
            return participante
        except Exception as e:
            return None
        return None

    def pre_inscribir_en_evento(self, evento_id):
        try:
            evento = Evento.revisar_existencia_evento(evento_id)
            if not evento:
                raise Exception("Evento no encontrado id %s"%evento_id)

            participacion = Inscripcion()
            participacion.participante = self
            participacion.evento = evento
            participacion.save()
            return participacion, "Usted se ha preinscrito correctamente"
        except Exception as e:
            print(e)
            return False, "Error al registrar la preinscripción"

    def obtener_codigo(self):
        codigo = (self.id * 56423) % 10012300207
        clave = "%d-%d" % (codigo, self.id)
        return clave

    @staticmethod
    def buscar_participante_codigo(codigo):
        try:
            mi_hash, mi_id  = map(int, codigo.split("-"))
            participante = Participante.objects.get(id=mi_id)
            if participante.obtener_codigo() == codigo:
                return participante
            else:
                return None
        except Exception as ex:
            return None

    def enviar_correo_recuperacion_codigo(self, request):
        participante = self

        mensaje = """
            Buen día participante %s.
            
            Ha solicitado el código para modificar sus datos personales
            
            El código para modificar sus datos personales es: %s.
        
            Puede modificar sus datos en %s

        """ % (participante, participante.obtener_codigo(), reverse_lazy('participante_codigo_participante'))

        datos_email = {
            "subject": "[Eventos ABC] Recuperación de código",
            "body": mensaje,
            "to": [participante.correo],
            "mensaje_error": "Error al enviar correo",
        }

        enviar_email(request, **datos_email)

    def __str__(self):
        return "%s %s"%(self.nombres,self.apellidos)


class Inscripcion(models.Model):
    ESTADO_INSCRIPCION = (
        ('EN ESPERA PRE', 'En espera de pre-inscripción'),
        ('PREINSCRITO', 'Preinscrito'),
        ('Rechazado', 'Rechazado'),
        ('PAGAR', 'A espera del pago'),
        ('PAGO', 'Pagado'),
        ('INSCRITO', 'Inscrito'),
    )

    participante = models.ForeignKey('Participante', related_name='eventos')
    evento = models.ForeignKey('Evento', related_name='participantes')
    estado_inscripcion = models.CharField(max_length=30, null = False, default= 'EN ESPERA PRE', choices= ESTADO_INSCRIPCION)


    @staticmethod
    def revisar_participacion(participante, evento):
        print(Inscripcion.objects.filter(participante = participante, evento = evento) is None)
        if not Inscripcion.objects.filter(participante = participante, evento = evento).exists():
            return False
        else:
            return True

    @staticmethod
    def get_participacion(participante, evento):
        try:
            participacion = Inscripcion.objects.get(participante__id = participante, evento__id = evento)
            #print(participacion)
            return participacion
        except Exception as e:
            print(e)
            return None
        return None


    def inscribir(self):
        try:
            self.estado_inscripcion = 'INSCRITO'
            self.save()
            return True
        except Exception as e:
            print(e)
            return False

    def enviar_correo_preinscripcion_aceptada(self, request):
        participante = self.participante
        evento = self.evento

        mensaje = """
            Buen día participante %s su pre-inscripción al evento %s ha sido aceptada exitosamente.

            Con el código %s puede modificar sus datos personales.
            
            Para completar su inscripción debe realizar el pago del evento en pagos.eventosabc.com.co con los siguientes datos:
            - Número de documento: %s
            - Identificador del evento: %s
            - Valor a pagar: %s
            
            Muchas gracias
        """ % (participante, evento, participante.obtener_codigo(), participante.numero_documento, evento.id, evento.costo)

        datos_email = {
            "subject": "[Eventos ABC] Pre-inscripción aceptada",
            "body": mensaje,
            "to": [participante.correo],
            "mensaje_error": "Error al enviar correo con información de la pre-inscripción aceptada, por favor informe al participante",
        }

        enviar_email(request, **datos_email)

    def enviar_correo_preinscripcion_rechazada(self, request):
        participante = self.participante
        evento = self.evento

        mensaje = """
            Buen día participante %s su pre-inscripción al evento %s ha sido rechazada.

            Muchas gracias
        """ % (participante, evento)

        datos_email = {
            "subject": "[Eventos ABC] Pre-inscripción rechazada",
            "body": mensaje,
            "to": [participante.correo],
            "mensaje_error": "Error al enviar correo con información de la pre-inscripción rechazada, por favor informe al participante",
        }
        enviar_email(request, **datos_email)


    def confirmar_pago_web_service(self, request):
        import requests
        from django.contrib import messages
        from django.conf import settings

        url_web_service = settings.URL_WEB_SERVICE
        datos = {
            'evento_id': self.evento.id,
            'numero_documento': self.participante.numero_documento,
            'valor': self.evento.costo
        }

        respuesta = requests.get(url_web_service, params=datos, verify=False)
        if respuesta.status_code == requests.codes.ok:
            estado_pago = respuesta.json()['estado_pago']
            if estado_pago == 'realizado':
                self.estado_inscripcion = 'PAGO'
                self.save()
                messages.success(request, "Pago confirmado exitosamente")
                return True
            if estado_pago == 'inexistente':
                pass

        messages.error(request, "No ha sido posible confirmar el pago")
        return False

proyectowww/apps/eventos/templates/calendario_evento.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %} Calendario evento {% endblock titulo %}

{% block titulo_pagina %}
    Calendario
{% endblock titulo_pagina %}


{% block titulo_panel %}
    Calendario del evento: {{ evento.nombre }}
    <button class="btn btn-default btn-sm" id="actualizar">
        <i class="ti-calendar "></i>
        Actualizar
    </button>
{% endblock titulo_panel %}

{% block css %}
    <link href="{% static 'plugins/fullcalendar/fullcalendar.min.css' %}" rel="stylesheet">
	<link href="{% static 'plugins/fullcalendar/nifty-skin/fullcalendar-nifty.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/fullcalendar/lib/moment.min.js' %}"></script>
	<script src="{% static 'plugins/fullcalendar/lib/jquery-ui.custom.min.js' %}"></script>
	<script src="{% static 'plugins/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'plugins/fullcalendar/lang/es.js' %}"></script>
{% endblock  %}

{% block js_propios %}
    <script>
        // Initialize the calendar
        // -----------------------------------------------------------------
        $('.calendar').fullCalendar({
            locale:'es',
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            editable: false,
            defaultDate: moment().format("YYYY-MM-DD"),
            eventLimit: true // allow "more" link when too many events
        });

    </script>

    <script src="{% static 'js/apps/evento/calendario_evento.js' %}"></script>

    <script>
        actualizarCalendario('{% url "evento_datos_calendario" %}',{{ evento.id }})
    </script>

{% endblock  %}


{% block contenido_panel %}

    <div class="row">
        <!-- ============================================ -->
        <div class='calendar col-sm-offset-0 col-sm-12 col-md-offset-2 col-md-8 '></div>
        <!-- ============================================ -->
    </div>

{% endblock contenido_panel %}

proyectowww/apps/eventos/templates/crear_escarapela.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block titulo %}
{{ nombre_evento }}
{% endblock titulo %}
{% block titulo_pagina %}
{% endblock titulo_pagina %}


{% block js_propios %}
    {{ block.super }}
    <script>
        //script que trasfiere los datos del evento al modal de confirmación
         $('#crear_escarapela').on (click,funcion).trigger ();
    </script>
{% endblock js_propios %}

{% block contenido_panel %}
<div class="row">
    <div class="panel-body col-xs-5">
        <div id="page-content">
            <img src="/static/img/image13.png" alt="Logo" class="mar-top" height="250" width="250">
            <address>
                <h2 class="text-main h2 text-uppercase text-thin mar-no text-primary">¡Hola! Me llamo: </h2>

                <h3 class="text-main h3 text-uppercase text-thin mar-no text-primary">
                    {{ participante.nombres }}
                    {{ participante.apellidos }}</h3>
            </address>
            <address>
                <h2 class="text-main h2 text-uppercase text-thin mar-no text-primary">Mi documento es: </h2>

                <h3 class="text-main h3 text-uppercase text-thin mar-no text-primary">
                    {{ participante.numero_documento }}</h3>
            </address>
            <address>
                <h2 class="text-main h2 text-uppercase text-thin mar-no text-primary">Y participo en: </h2>

                <h3 class="text-main h3 text-uppercase text-thin mar-no text-primary">
                    {{ evento.nombre }}</h3>
            </address>
            <div class="text-right no-print">
                <a href="{% url 'inscribir_en_evento' evento.id %}" class="btn btn-danger btn-lg">Volver</a>
                <a href="javascript:window.print()" class="btn btn-info btn-lg">
                    <span class="glyphicon glyphicon-print"></span> Imprimir
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock contenido_panel %}

proyectowww/apps/eventos/templates/crear_evento.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %} Registrar evento {% endblock titulo %}

{% block titulo_pagina %}
    Registrar evento
{% endblock titulo_pagina %}



{% block titulo_panel %}
    Formulario de registrio
{% endblock titulo_panel %}




{% block contenido_panel %}


    <form action = "" method="POST" class="form-horizontal form-bordered "  enctype="multipart/form-data"  data-parsley-validate="true"> {% csrf_token %}
        <div class="col-sm-offset-2 col-sm-8">{% for campo in form %}
            {% bootstrap_field campo layout='horizontal' %}
        {% endfor %}
            <div class="col-md-12 col-sm-12 ">
                <span class="pull-right">
                    <a href="{% if request.META.HTTP_REFERER %} {{ request.META.HTTP_REFERER }} {% else %} {% url 'evento_listar' %} {% endif %}" class="btn btn-danger ">Cancelar</a>
                    <button type="submit" class="btn btn-primary pull-right" style="margin-left: 5px">Registrar</button>
                </span>
            </div>
        </div>
    </form>


{% endblock contenido_panel %}

proyectowww/apps/eventos/templates/dashboard_eventos.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %} Eventos {% endblock titulo %}

{% block titulo_pagina %}
    Eventos 
{% endblock titulo_pagina %}



{% block titulo_panel %}
    Eventos
{% endblock titulo_panel %}




{% block contenido %}
                                    
                                    {% for evento in lista_eventos %}
                                    <div class="row-sm-4" >
                                    <div class="col-sm-6 col-xs-12 col-md-4">
                                    <div class="panel">
					                    <div class="panel-body text-center bg-mint">

					                        	<a href="{% url 'inscribir_en_evento' evento.id %}"><img class="img-lg img-circle img-border mar-btm" src="{% if evento.imagen %}
                                                                 {{ MEDIA_URL }}{{ evento.imagen }} 
                                                                 {% else %}
                                                                 {% static 'img/image13.png'%}
                                                                 {% endif %}" alt="Foto evento"></a>
					
					                        <h4 class="text-light">{{ evento.nombre }}</h4>
					                        <p class="text-sm">{{ evento.descripcion }}</p>
					                        <ul class="list-unstyled text-center pad-top mar-no row">
					                            <li class="col-xs-4">
					                                <span class="text-lg text-semibold">{{evento.numero_cupos}}</span>
					                                <p class="text-sm mar-no">Número de cupos</p>
					                            </li>
					                            <li class="col-xs-4">
					                                <span class="text-lg text-semibold">{{evento.fecha_inicio|date:"M d, Y"}}</span>
					                                <p class="text-sm mar-no">Fecha inicio</p>
					                            </li>
					                            <li class="col-xs-4">
					                                <span class="text-lg text-semibold">{{evento.fecha_fin|date:"M d, Y"}}</span>
					                                <p class="text-sm mar-no">Fecha fin</p>
					                            </li>
					                        </ul>
					                    </div>
					                    <div class="list-group bg-trans pad-btm">
					                        <a class="list-group-item" href="#"><i class="demo-pli-information icon-lg icon-fw"></i><b>Dirección:</b> {{ evento.direccion }}</a>
					                        <a class="list-group-item" href="#"><i class="demo-pli-mine icon-lg icon-fw"></i><b>Teléfono:</b> {{ evento.telefono }}</a>
					                        <a class="list-group-item" href="#"><span class="label label-info pull-right">Promoción</span><i class="demo-pli-credit-card-2 icon-lg icon-fw"></i><b>Costo:</b> {{ evento.costo }}</a>
					                    </div>
					                </div>
					                </div>
					                </div>
					                {% endfor %}

{% endblock contenido %}

proyectowww/apps/eventos/templates/inscripcion.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %} Inscribir {% endblock titulo %}

{% block titulo_pagina %}
    Inscribir
{% endblock titulo_pagina %}


{% block titulo_panel %}
    Inscribir
{% endblock titulo_panel %}

{% block contenido_panel %}


    <form action = "" method="POST" class="form-horizontal form-bordered " data-parsley-validate="true"> {% csrf_token %}
        <div class="col-sm-offset-2 col-sm-8">{% for campo in form %}
            {% bootstrap_field campo layout='horizontal' %}
        {% endfor %}
            <div class="col-md-12 col-sm-12 ">
                <span class="pull-right">
                    <a href="{% if request.META.HTTP_REFERER %} {{ request.META.HTTP_REFERER }} {% else %} {% url 'evento_listar' %} {% endif %}" class="btn btn-danger ">Cancelar</a>
                    <button type="submit" class="btn btn-primary pull-right" style="margin-left: 5px">Inscribir</button>
                </span>
            </div>
        </div>
    </form>


{% endblock contenido_panel %}

proyectowww/apps/eventos/templates/listado_preinscrito.html
{% extends 'base_tablas.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %}
    Lista de preinscritos
{% endblock titulo %}

{% block titulo_pagina %}
    Lista de preinscritos
{% endblock titulo_pagina %}

{% block titulo_panel %}
    Lista de preinscritos
{% endblock titulo_panel %}


{% block js_propios %}
    {{ block.super }}
    <script>
        //script que trasfiere los datos del preinscrito al modal de confirmación
        $(".cambiar-estado").on('click', function (e) {
            var url = $(this).attr('data-url');
            var nombre = $(this).data('preinscrito-nombre');
            var apellidos = $(this).data('preinscrito-apellidos');
            var documento = $(this).data('preinscrito-documento');
            var titulo = $(this).data('titulo');
            var texto = $(this).data('texto');

            $(".preinscrito-nombre").text(nombre);
            $(".preinscrito-apellidos").text(apellidos);
            $(".preinscrito-documento").text(documento);
            $(".titulo").text(titulo);
            $(".texto").text(texto);
            $("#confirmar-cambio").attr('href', url);

        });


    </script>
{% endblock js_propios %}

{% block botones_panel %}
{% endblock botones_panel %}

{% block contenido_panel %}
    <div class="table-responsive  dataTables_wrapper">
        <table class="table table-striped table-bordered  data-combine">
            <thead>
            <tr>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Número de identificación</th>
                <th>Correo</th>
                <th>Teléfono</th>
                <th>Estado</th>
                <th>Opciones</th>
             
                
            </tr>
            </thead>
            <tbody>
            {% if user.cargo == "Operador" %}
                {% for preinscrito in evento.participantes.all %}
                    <tr>
                        <td>{{ preinscrito.participante.nombres }}</td>
                        <td>{{ preinscrito.participante.apellidos }}</td>
                        <td>{{ preinscrito.participante.numero_documento}}</td>
                        <td>{{ preinscrito.participante.correo }}</td>
                        <td>{{ preinscrito.participante.telefono }}</td>
                        <td>{{ preinscrito.get_estado_inscripcion_display }} </td>
                        <td>

                            {% if preinscrito.estado_inscripcion == 'EN ESPERA PRE' %}
                                <a data-toggle="modal" data-target="#modal-confirmacion" href="#"
                                   data-url="{% url 'aceptar_preinscrito' preinscrito.evento.id preinscrito.id   %}"
                                   data-preinscrito-nombre="{{ preinscrito.participante.nombres }}"
                                   data-preinscrito-apellidos = "{{ preinscrito.participante.apellidos }}"
                                   data-preinscrito-documento="{{ preinscrito.participante.numero_documento}}"
                                   data-titulo="Aceptar"
                                   data-texto="aceptar"
                                   class="btn btn-xs btn-success cambiar-estado">
                                        Aceptar inscripción
                                </a>

                                <a data-toggle="modal" data-target="#modal-confirmacion" href="#"
                                   data-url="{% url 'rechazar_preinscrito' preinscrito.evento.id preinscrito.id  %}"
                                   data-preinscrito-nombre="{{ preinscrito.participante.nombres }}"
                                   data-preinscrito-apellidos = "{{ preinscrito.participante.apellidos }}"
                                   data-preinscrito-documento="{{ preinscrito.participante.numero_documento}}"
                                   data-titulo="Rechazar"
                                   data-texto="rechazar"
                                   class="btn btn-xs btn-danger cambiar-estado">
                                        Rechazar inscripción
                                </a>
                            {% elif preinscrito.estado_inscripcion == 'PREINSCRITO' %}
                                Ya se encuentra pre-inscrito
                            {% elif preinscrito.estado_inscripcion == 'Rechazado' %}
                                La inscripción fue rechazada
                            {% elif preinscrito.estado_inscripcion == 'INSCRITO' %}
                                Ya se encuentra inscrito
                            {% endif %}

                            <a href="{% url 'participante_modificar' preinscrito.evento.id preinscrito.participante.id %}"
                               class="btn btn-primary btn-xs">Modificar</a>

                        </td>                        
                    </tr>

                {% endfor %}
            
            {% endif %}

            </tbody>
        </table>
    </div>

    <div class="modal inmodal" id="modal-confirmacion">
        <div class="modal-dialog">
            <div class="modal-content animated bounceInRight">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title"><label class="titulo"></label> preinscripción del participante</h4>
                </div>
                <div class="modal-body">
                    <p> ¿Está seguro que desea <label class="texto"></label> la preinscripción del participante?</p>
                    <ul>
                        <li><b>Nombre</b>: <label class="preinscrito-nombre"></label> <label class="preinscrito-apellidos"></label></li>
                        <li><b>Número de identificación</b>: <label class="preinscrito-documento"></label></li>
                    </ul>

                </div>
                <div class="modal-footer">
                    <a id="confirmar-cambio" href="" class="btn btn-sm btn-danger">Confirmar</a>
                    <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Cancelar</a>
                </div>
            </div>
        </div>
    </div>

        <div class="modal inmodal" id="modal-confirmacion2">
        <div class="modal-dialog">
            <div class="modal-content animated bounceInRight">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title">Rechazar preinscripción de participante</h4>
                </div>
                <div class="modal-body">
                    <p> ¿Está seguro que desea rechazar la preinscripción del participante?</p>
                    <ul>
                        <li><b>Nombre</b>: <label class="preinscrito-nombre"></label> <label class="preinscrito-apellidos"></label></li>
                        <li><b>Número de identificación:</b> <label class="preinscrito-documento"></label></li>
                    </ul>

                </div>
                <div class="modal-footer">
                    <a id="confirmar-cambio" href="" class="btn btn-sm btn-danger">Confirmar</a>
                    <a href="javascript:;" class="btn btn-sm btn-white" data-dismiss="modal">Cancelar</a>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido_panel %}

proyectowww/apps/eventos/templates/modificar_datos_codigo_participante.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block titulo %} Modificar evento {% endblock titulo %}

{% block titulo_pagina %}
    Modificar evento
{% endblock titulo_pagina %}


{% block titulo_panel %}
    Modificar evento
{% endblock titulo_panel %}

{% block contenido_panel %}


    <form action = "" method="POST" class="form-horizontal form-bordered "  enctype="multipart/form-data"  data-parsley-validate="true"> {% csrf_token %}
        <div class="col-sm-offset-2 col-sm-8">{% for campo in form %}
            {% bootstrap_field campo layout='horizontal' %}
        {% endfor %}
            <div class="col-md-12 col-sm-12 ">
                <span class="pull-right">
                    <a href="{% if request.META.HTTP_REFERER %} {{ request.META.HTTP_REFERER }} {% else %} {% url 'evento_listar' %} {% endif %}" class="btn btn-danger ">Cancelar</a>
                    <button type="submit" class="btn btn-primary pull-right" style="margin-left: 5px">Enviar</button>
                </span>
            </div>
        </div>
    </form>


{% endblock contenido_panel %}

proyectowww/apps/eventos/templates/modificar_datos_personales_participante.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block titulo %} 
	Modificar datos personales
{% endblock titulo %}

{% block titulo_pagina %}
    Modificar datos personales
{% endblock titulo_pagina %}


{% block titulo_panel %}
    Modificar datos personales
{% endblock titulo_panel %}

{% block clase_ancho_panel  %}col-sm-7{% endblock clase_ancho_panel  %}

{% block contenido_panel %}

	<form action="" method="post" class="form-horizontal form-bordered " data-parsley-validate="true"> 
	{% csrf_token %}
	{% for campo in form %}
        {% bootstrap_field campo layout='horizontal' %}
    {% endfor %}

    <div class="col-md-12 col-sm-12 ">
            
            <button type="submit" class="btn btn-primary pull-right">Enviar</button>
        </div>
    </form>


{% endblock contenido_panel %}